#!/bin/bash

pushd ~/.aws/sso/cache > /dev/null

tokenFile=$(grep -r $(aws configure get sso_start_url) | cut -f1 -d:)
token=$(cat $tokenFile | jq .accessToken -r)

output=$(aws sso get-role-credentials \
  --role-name $(aws configure get sso_role_name) \
  --account-id $(aws configure get sso_account_id) \
  --access-token $token)

echo export AWS_ACCESS_KEY_ID=$(echo $output | jq -c '.roleCredentials.accessKeyId' | tr -d '"' | tr -d ' ')
echo export AWS_SECRET_ACCESS_KEY=$(echo $output | jq -c '.roleCredentials.secretAccessKey' | tr -d '"' | tr -d ' ')
echo export AWS_SESSION_TOKEN=$(echo $output  | jq -c '.roleCredentials.sessionToken' | tr -d '"' | tr -d ' ')

popd > /dev/null