#!/bin/bash

mkdir -p ~/bin
if [ -x ~/bin/k9s ]; then
  ~/bin/k9s version
fi

pushd ~/bin

echo "==> Checking latest version"
url=$(curl -sS https://api.github.com/repos/derailed/k9s/releases/latest | jq -r '.assets[].browser_download_url' | grep arm\\.)

echo "==> Downloading k9s"

curl -sS -L $url > k9s.tgz

echo "==> Unpacking k9s"

tar -zxvf k9s.tgz
rm LICENSE README.md
rm k9s.tgz

popd
~/bin/k9s version

echo "==> All done"
